[package]
name = "rust_dojo"
version = "0.1.0"
authors = ["Jabster28 <justynboyer@gmail.com>"]
edition = "2018"


[lib]
name = "dojo"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[badges]
maintenance = { status = "as-is" }

[dependencies]
